baseURL = "https://prashantshahi.dev/"
languageCode = "en-us"
title = "Prashant's Scrapbook"
description = "Personal Website"
theme = "ananke"
show_reading_time = true
copyright = "prashantshahi.dev"
disqusShortname = "prashantshahi"

[params]
    env = "production"

[[menu.main]]
  name = "Home"
  url = "/"
  identifier = "home"
  weight = -1
[[menu.main]]
  name = "Blog"
  url = "/blog"
  identifier = "blog"
  weight = 1
[[menu.main]]
  name = "About"
  url = "/#about"
  identifier = "about"
  weight = 2
